const mongoose = require('mongoose');
const requireLogin = require('../middlewares/requireLogin');
const requireCredits = require('../middlewares/requireCredits');

const Survey = mongoose.model('surveys');

module.exports = app => {
	/*
		Create a new survey and send out a big email
	*/
	app.post('/api/surveys', requireLogin, requireCredits, (req,res) => {
		const { title, subject, body, recipients } = req.body;

		/*
			Note that: 
			1. (email => {return {email:email}}) 
			   is condensed to:
			   (email => ({ email }))
			2. req.user.id is generated by mongo
		*/
		const survey = new Survey({
			title,
			subject,
			body,
			recipients: recipients.split(',').map(email => ({ email })),
			_user: req.user.id,
			dateSent: Date.now()
		});
	});
};